apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.payments.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.payments.name }}
    tier: backend
    {{ include "day5-ecommerce.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.payments.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.payments.name }}
        tier: backend
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo '<h1>{{ .Values.payments.message }}</h1><p>Installed with Helm release {{ .Release.Name }}</p>' > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

